[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "/opt/venv/bin/streamlit run wizard_streamlit_app.py --server.port=8080 --server.address=0.0.0.0" 