[phases.setup]
nixPkgs = ["python310", "poetry"]

[phases.install]
cmds = ["poetry install --no-dev"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "poetry run streamlit run wizard_streamlit_app.py --server.port=$PORT --server.address=0.0.0.0" 